title: Andrew Friedemann
author: 
  name: Andrew Friedemann
  email: andrewsfriedemann@gmail.com
url: https://www.andrewfriedemann.com
description: A site built with Jekyll, hosted by GitHub Pages.

minima:
  social_links:
    github: andrewfriedemann
    linkedin: andrew-friedemann

theme: minima
