title: Home
author:
  name: Andrew Friedemann
  email: andrewsfriedemann@gmail.com
headline: https://github.com/andrewfriedemann
description: A site built with Jekyll, hosted by GitHub Pages.

minima:
  skin: dark
  social_links:
    github: andrewfriedemann
    linkedin: andrew-friedemann

theme: minima
