title: Home
author: Andrew Friedemann
email: andrewsfriedemann@gmail.com
url: https://www.andrewfriedemann.com/
headline: https://github.com/andrewfriedemann
description: A site built with Jekyll, hosted by GitHub Pages.
github_username: andrewfriedemann
linkedin_username: andrew-friedemann

theme: minima
